#pragma once

typedef enum ControllerId
{
    CONTROLLER_UNASSIGNED = -1,
    CONTROLLER_KEYBOARD1,
    CONTROLLER_KEYBOARD2,
    CONTROLLER_GAMEPAD1,
    CONTROLLER_GAMEPAD2,
    CONTROLLER_GAMEPAD3,
    CONTROLLER_GAMEPAD4
} ControllerId;
